### ISSUE TITLE
App crash when you remove last tab from side navigation on Android 10

### ISSUE THREAD

**Issue by RanbirSingh** [jamal2362/Styx#2]
Hi there
great job app browser is really fast and performance is really good.
app is crashed when last tab is cleared app closed and crashed.

here is log for crash
2021-01-21 16:37:39.415 1337-1337/com.jamal2367.stxy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jamal2367.stxy, PID: 1337
    java.lang.RuntimeException: Unable to destroy activity {com.jamal2367.stxy/com.jamal2367.styx.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.jamal2367.styx.download.StyxDownloadListener@3d10328
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5036)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5065)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7564)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.jamal2367.styx.download.StyxDownloadListener@3d10328
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1433)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1553)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:674)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:674)
        at f.c.a.i0.u.Q(:730)
        at f.c.a.j.d.l(:136)
        at f.c.a.j.d.q(:333)
        at com.jamal2367.styx.browser.activity.BrowserActivity.onDestroy(:1609)
        at android.app.Activity.performDestroy(Activity.java:8203)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5021)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5065) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:225) 
        at android.app.ActivityThread.main(ActivityThread.java:7564) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by jamal2362** [comment]
Thank you for the report.
The bug is fixed.
https://github.com/jamal2362/Styx/commit/cf0958026b6b054a4c1d5f8d7d4199bd37c825a6
